#!/usr/bin/bash

set -e

wasm-pack build --target web
rm -rf ../../../cabin-language.github.io/src/wasm/cabin
mkdir ../../../cabin-language.github.io/src/wasm/cabin
cp ./pkg/* ../../../cabin-language.github.io/src/wasm/cabin
